Name: Docker CI
On:
 push:
  Branch:
   - master

Jobs:
 Build-and-Push:
 Runs-on: ubuntu-latest

 steps:

 - name: Checkout code
   uses: actions/checkout@v3

 - name: Login To Docker
   uses: docker/login-action@v2
   with: 
    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

 - name:
   run: |
        IMAGE_TAG=${{ github.repository }}:${{github.sha}}
        LATEST_TAG=${{ github.sha }}:latest
        docker build -t $IMAGE_TAG .
        docker tag $IMAGE_TAG $LATEST_TAG

 - name:
   run: |
        IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
        LATEST_TAG=${{ github.sha }}:latest
        docker push $IMAGE_TAG
        docker push $LATEST_TAG       