Name: Docker CI
On:
 push:
  branch: 
   - master

Jobs:
 Build-and_push:
 Runs-on: ubuntu-latest

 steps:
 - name: code checkout
   uses: actions/checkout@v3

 - name: login to docker
   uses: docker/login-action@v2
   with:
    username: ${{secrets.DOCKER_HUB_USERNAME}}
    password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

 - name: get Short SHA
   id: vars
   run: echo "SHORT_SHA=$(git rev prase --short HEAD)" >> GITHUB_ENV

 - name: build docker image
   run: |
        IMAGE_TAG=${{github.repository}}:${{env.SHORT_SHA}}
        LATEST_TAG=${{github.repository}}:latest
        docker build -t $IMAGE_TAG .
        docker tag $IMAGE_TAG $LATEST_TAG

 - name: push docker image
   run: |
        IMAGE_TAG=${{github.repository}}:${{env.SHORT_SHA}}
        LATEST_TAG=${{github.repository}}:latest
        docker push $IMAGE_TAG
        docker push $LATEST_TAG
